package ru.example.qa.notesapp.util

object Keys {
    const val APP_SHARED_PREFS = "NOTESAPP_SHARED_PREFS"
    const val USER_USERNAME_PREF = "USER_USERNAME_PREF"
    const val USER_PASSWORD_HASH_PREF = "USER_PASSWORD_HASH_PREF"

    const val NOTE_MENU_DIALOG_RESULT_KEY = "NOTE_MENU_DIALOG_RESULT_KEY"
    const val NOTE_DELETE_CONFIRMATION_DIALOG_RESULT_KEY = "NOTE_DELETE_CONFIRMATION_DIALOG_RESULT_KEY"
}